# Site settings
title: logTank
email: peter.grman@logtank.com
description: > # this means to ignore newlines until "baseurl:"
  A blog with tips and tricks on how you can collect useful and actionable data from your applications in order to improve them and provide your users with a better experience.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.logtank.com" # the base hostname & protocol for your site
twitter_username: log_tank
github_username:  logtank
permalink: "/:title/"
google_analytics_id: UA-40793217-3

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
    values:
      author: "logTank"
      greeting: "Just add Data ♥"